---
title       : SiliDog Nike ID Project
subtitle    : Personalize your dog tag!
author      : Anonymous
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## SiliDog

The latest in canine fashion.
These tags are revolutioning the way tags are worn.

Made of a special silicone, these tags
- Never Wear
- Never Tear
- And most of all, DO NOT JINGLE!


--- .class #id 

## Shiny App

This Shiny app was made as a prototype to a javascript applet which is
similar to Nike ID's customization ability, but for dog tags!

It is being worked on everyday, but currently, you are able to 

* Choose your style of tag from 4 current styles
  ```{r, echo=F,warning=F}
  print('Bone, Circle, Heart, Fire Hydrant')
  ```
* Input your pet's name
* Input your phone number

--- .class #id

## Shiny App Continued

Currently, you are only able to design the front of your tag.

Soon, capabilities will include

* Customizing the back of the tag
  + Input addresses
  + Input microchip numbers
* Directly place your order through this applet


  



---
## Thank you


Thank you for using my app, and I look forward to the feedback I will receive!





